setAll(red)
await display()
await delay(2000)
setAll(red)
setPixel(5, 10, white)
setPixel(5, 9, white)
setPixel(5, 8, white)
setPixel(5, 7, white)
setPixel(5, 6, white)
setPixel(5, 5, white)
setPixel(5, 4, white)
setPixel(5, 3, white)
setPixel(5, 2, white)
await display()

await delay(5000)
setAll(red)
setPixel(5, 9, white)

setPixel(6, 10, white)
setPixel(4, 10, white)

setPixel(7, 10, white)
setPixel(3, 10, white)

setPixel(8, 9, white)
setPixel(7, 9, white)
setPixel(6, 9, white)
setPixel(5, 9, white)
setPixel(4, 9, white)
setPixel(3, 9, white)
setPixel(2, 9, white)

setPixel(8, 8, white)
setPixel(7, 8, white)
setPixel(6, 8, white)
setPixel(5, 8, white)
setPixel(4, 8, white)
setPixel(3, 8, white)
setPixel(2, 8, white)

setPixel(8, 7, white)
setPixel(7, 7, white)
setPixel(6, 7, white)
setPixel(5, 7, white)
setPixel(4, 7, white)
setPixel(3, 7, white)
setPixel(2, 7, white)

setPixel(7, 6, white)
setPixel(7, 6, white)
setPixel(6, 6, white)
setPixel(5, 6, white)
setPixel(4, 6, white)
setPixel(3, 6, white)

setPixel(6, 5, white)
setPixel(5, 5, white)
setPixel(4, 5, white)


setPixel(5, 4, white)

await display()

await delay(5000)

setAll(red)
setPixel(2, 10, white)
setPixel(2, 9, white)
setPixel(2, 8, white)
setPixel(2, 7, white)
setPixel(2, 6, white)
setPixel(2, 5, white)
setPixel(2, 4, white)
setPixel(2, 3, white)
setPixel(2, 2, white)

setPixel(8, 10, white)
setPixel(8, 9, white)
setPixel(8, 8, white)
setPixel(8, 7, white)
setPixel(8, 6, white)
setPixel(8, 5, white)
setPixel(8, 4, white)
setPixel(8, 3, white)
setPixel(8, 2, white)

setPixel(8, 2, white)
setPixel(7, 2, white)
setPixel(6, 2, white)
setPixel(5, 2, white)
setPixel(4, 2, white)
setPixel(3, 2, white)

await display()

await delay(500)
setAll(red)
await display()
await delay(500)
setAll(red)
setPixel(2, 10, white)
setPixel(2, 9, white)
setPixel(2, 8, white)
setPixel(2, 7, white)
setPixel(2, 6, white)
setPixel(2, 5, white)
setPixel(2, 4, white)
setPixel(2, 3, white)
setPixel(2, 2, white)

setPixel(8, 10, white)
setPixel(8, 9, white)
setPixel(8, 8, white)
setPixel(8, 7, white)
setPixel(8, 6, white)
setPixel(8, 5, white)
setPixel(8, 4, white)
setPixel(8, 3, white)
setPixel(8, 2, white)

setPixel(8, 2, white)
setPixel(7, 2, white)
setPixel(6, 2, white)
setPixel(5, 2, white)
setPixel(4, 2, white)
setPixel(3, 2, white)
await display()

await delay(500)
setAll(red)
await display()

await delay(500)
setAll(red)
setPixel(2, 10, white)
setPixel(2, 9, white)
setPixel(2, 8, white)
setPixel(2, 7, white)
setPixel(2, 6, white)
setPixel(2, 5, white)
setPixel(2, 4, white)
setPixel(2, 3, white)
setPixel(2, 2, white)

setPixel(8, 10, white)
setPixel(8, 9, white)
setPixel(8, 8, white)
setPixel(8, 7, white)
setPixel(8, 6, white)
setPixel(8, 5, white)
setPixel(8, 4, white)
setPixel(8, 3, white)
setPixel(8, 2, white)

setPixel(8, 2, white)
setPixel(7, 2, white)
setPixel(6, 2, white)
setPixel(5, 2, white)
setPixel(4, 2, white)
setPixel(3, 2, white)
await display()

await delay(500)
setAll(red)
await display()

await delay(500)
setAll(red)
setPixel(2, 10, white)
setPixel(2, 9, white)
setPixel(2, 8, white)
setPixel(2, 7, white)
setPixel(2, 6, white)
setPixel(2, 5, white)
setPixel(2, 4, white)
setPixel(2, 3, white)
setPixel(2, 2, white)

setPixel(8, 10, white)
setPixel(8, 9, white)
setPixel(8, 8, white)
setPixel(8, 7, white)
setPixel(8, 6, white)
setPixel(8, 5, white)
setPixel(8, 4, white)
setPixel(8, 3, white)
setPixel(8, 2, white)

setPixel(8, 2, white)
setPixel(7, 2, white)
setPixel(6, 2, white)
setPixel(5, 2, white)
setPixel(4, 2, white)
setPixel(3, 2, white)
await display()

await delay(2000)

